services:

  db:
    image: postgres:latest
    container_name: videoflix_database
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:latest
    container_name: videoflix_redis
    volumes:
      - redis_data:/data

  web:
    build:
      context: .
      dockerfile: backend.Dockerfile
    env_file: .env
    container_name: videoflix_backend

    volumes:
      - .:/app
      # - videoflix_media:/app/media
      - ./media:/app/media
      - videoflix_static:/app/static
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
      - redis

  # DEIN NEUER WORKER SERVICE:
  rqworker:
    build:
      context: .
      dockerfile: backend.Dockerfile
    env_file: .env
    container_name: videoflix_worker
    command: python manage.py rqworker default
    volumes:
      - .:/app
      - ./media:/app/media
      - videoflix_static:/app/static
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - web
      - redis

volumes:
  postgres_data:
  redis_data:
  videoflix_media:
  videoflix_static:
