# Generated by Django 6.0.7 on 2026-08-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Upload time')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video-file')),
            ],
        ),
    ]
