# Generated by Django 6.0.7 on 2026-08-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_video_video_1080p_video_video_480p_video_video_720p'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_hls',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='HLS Video'),
        ),
    ]
