# Generated by Django 6.0.7 on 2026-08-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_video_video_hls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='upload_date',
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation time'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True, verbose_name='Thumbnail URL'),
        ),
    ]
