# Generated by Django 6.0.7 on 2026-08-10 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_video_upload_date_video_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_1080p',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_480p',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_720p',
        ),
    ]
